### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by kex0** [kex0/batch-face-swap#55]
- [ ] Add ControlNet functionality #54 
- [ ] Add Wildcards functionality #47 
- [ ] Adjust "Only masked padding, pixels" and "Mask blur" based on face contour area

**Comment by atabatic** [comment]
@kex0 Hi Kex, I have a large library of previously-generated images where I'd like to add padding to the face detection. This is due to the amount of hair I include. Willing to donate $50. Thanks!
